-- Get count from all tables
SELECT COUNT(*) FROM REGION;
SELECT COUNT(*) FROM COUNTRY;
SELECT COUNT(*) FROM LOCATION;
SELECT COUNT(*) FROM WAREHOUSE;
SELECT COUNT(*) FROM EMPLOYEE;
SELECT COUNT(*) FROM PRODUCT_CATEGORY;
SELECT COUNT(*) FROM PRODUCT;
SELECT COUNT(*) FROM CUSTOMER;
SELECT COUNT(*) FROM CONTACT;
SELECT COUNT(*) FROM ORDER_ENTRY;
SELECT COUNT(*) FROM ORDER_ITEM;
SELECT COUNT(*) FROM INVENTORY;

-- Delete all Data from tables
DELETE FROM INVENTORY;
DELETE FROM ORDER_ITEM;
DELETE FROM ORDER_ENTRY;
DELETE FROM PRODUCT;
DELETE FROM CONTACT;
DELETE FROM WAREHOUSE;
DELETE FROM PRODUCT_CATEGORY;
DELETE FROM CUSTOMER;
DELETE FROM EMPLOYEE;
DELETE FROM COUNTRY;
DELETE FROM LOCATION;
DELETE FROM REGION;
